In [148]:
import pandas as pd
import numpy as np
import networkx as nx

In [149]:
path = 'C:/Users/ah3wj/Desktop/epi-segmentation/'
df = pd.read_csv(path + 'covid-19-dataset/us-counties.csv')

In [150]:
df.head()

date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1       0
1  2020-01-22  Snohomish  Washington  53061.0      1       0
2  2020-01-23  Snohomish  Washington  53061.0      1       0
3  2020-01-24       Cook    Illinois  17031.0      1       0
4  2020-01-24  Snohomish  Washington  53061.0      1       0

In [151]:
df.county.head()

0    Snohomish
1    Snohomish
2    Snohomish
3         Cook
4    Snohomish
Name: county, dtype: object

In [152]:
df['date'] = df['date'].astype('datetime64[ns]')

In [153]:
df.sort_values(by = ['date'], inplace = True, ascending = True)

In [154]:
all_dates = df.date.unique()
print(len(all_dates))

94


In [155]:
df_counties = df['county']  + ':' +df['state']
all_counties = df_counties.unique()
print(len(all_counties))

2836


In [156]:
def preprocess(lookup, resolution):
  with open(path + 'covid-19-dataset/processed-data/processed-us-counties-' + lookup + '.csv', 'w+') as lookup_file:

    with open(path + 'covid-19-dataset/processed-data/us-counties-order.csv', 'w+')  as order_file:

      for x in all_counties:
        county, state = x.split(':') 
#         print(county + '\n', end='')
        order_file.write(county + '\n')

        for date in all_dates:
          filter1 = df[resolution] == county
          filter2 = df['state'] == state
          filter3 =  df['date'] == date

          if((filter1 & filter2 & filter3).any()):
            value = df.loc[filter1 & filter2 & filter3][lookup].to_string(index=False)
#             if(not value.isnumeric()):
#               value = '0'
          else:
            value = '0'

          if(date == all_dates[-1]):
#             print(value , end='')
            lookup_file.write(value)
          else:
#             print(value + ', ', end='')
            lookup_file.write(value + ', ')

#         print('\n')
        lookup_file.write('\n')

In [157]:
########################### careful here 
########################################
########################################

lookup = 'cases'
resolution = 'county'

preprocess(lookup= lookup, resolution = resolution)


KeyboardInterrupt: 

In [51]:
with open(path + 'covid-19-dataset/processed-data/us-counties-order.csv', 'w+')  as order_file:
  for x in all_counties:
    order_file.write(x + '\n')        


**Now Time to Verify**

In [37]:
filename = path + 'covid-19-dataset/processed-data/processed-us-counties-' + lookup + '.csv'
verification = np.loadtxt(filename, dtype=int, delimiter=',')

print(verification)

[[    1     1     1 ...  2162  2208  2239]
 [    0     0     0 ... 23181 24546 25811]
 [    0     0     0 ...  1691  1753  1827]
 ...
 [    0     0     0 ...     0     0     1]
 [    0     0     0 ...     0     0     1]
 [    0     0     0 ...     0     0     1]]


In [25]:
# flag = False

# for i in range(len(verification)):

#   if(flag):
#     break
    
#   county = all_counties[i]   
# #   print(state)
#   for j in range(len(verification[i])):
#     if(verification[i][j] != 0):
#       date = all_dates[j]

# #       print(date)
      
#       df_of_county = df[df[resolution]== county]
#       df_of_time = df_of_county[df_of_county['date'] == date]
#       value = int(df_of_time[lookup].to_string(index=False))
      
#       assert value == verification[i][j]
#       if( value != verification[i][j]):
#         print("Doesn't match", state, date)
#         print('verif index: ', j, 'value: ', verification[i][j])
#         print('actual: ', value)
#         flag = True
#         break
        

In [52]:
counties_order = pd.read_csv(path+'covid-19-dataset/processed-data/us-counties-order.csv', header=None, encoding = "ISO-8859-1")

In [53]:
data = pd.read_csv(path+'covid-19-dataset/processed-data/processed-us-counties-cases.csv', header=None)

In [54]:
counties_order.head()

0
0    Snohomish:Washington
1           Cook:Illinois
2       Orange:California
3        Maricopa:Arizona
4  Los Angeles:California

In [55]:
data.head()

0   1   2   3   4   5   6   7   8   9   ...     84     85     86     87  \
0   1   1   1   1   1   1   1   1   1   1  ...   1949   1987   2031   2055   
1   0   0   0   1   1   1   1   1   1   2  ...  16323  17306  18087  19391   
2   0   0   0   0   1   1   1   1   1   1  ...   1299   1376   1425   1501   
3   0   0   0   0   0   1   1   1   1   1  ...   2056   2146   2264   2404   
4   0   0   0   0   0   1   1   1   1   1  ...  10047  10496  10854  11391   

      88     89     90     91     92     93  
0   2092   2142   2162   2162   2208   2239  
1  20395  21272  22101  23181  24546  25811  
2   1556   1636   1676   1691   1753   1827  
3   2491   2589   2636   2738   2846   2970  
4  12021  12341  13816  15140  16435  17508  

[5 rows x 94 columns]

In [56]:
frames = [counties_order, data]

In [57]:
result = pd.concat(frames, axis = 1)

In [58]:
result.head()

0   0   1   2   3   4   5   6   7   8   ...     84  \
0    Snohomish:Washington   1   1   1   1   1   1   1   1   1  ...   1949   
1           Cook:Illinois   0   0   0   1   1   1   1   1   1  ...  16323   
2       Orange:California   0   0   0   0   1   1   1   1   1  ...   1299   
3        Maricopa:Arizona   0   0   0   0   0   1   1   1   1  ...   2056   
4  Los Angeles:California   0   0   0   0   0   1   1   1   1  ...  10047   

      85     86     87     88     89     90     91     92     93  
0   1987   2031   2055   2092   2142   2162   2162   2208   2239  
1  17306  18087  19391  20395  21272  22101  23181  24546  25811  
2   1376   1425   1501   1556   1636   1676   1691   1753   1827  
3   2146   2264   2404   2491   2589   2636   2738   2846   2970  
4  10496  10854  11391  12021  12341  13816  15140  16435  17508  

[5 rows x 95 columns]

In [59]:
correct_format = result.T

In [133]:
correct_format.to_csv(path+'covid-19-dataset/processed-data/correct-county-cases.csv', header = False, index = False)

In [132]:
correct_format

0              1                  2                 3     \
0   Snohomish:Washington  Cook:Illinois  Orange:California  Maricopa:Arizona   
0                      1              0                  0                 0   
1                      1              0                  0                 0   
2                      1              0                  0                 0   
3                      1              1                  0                 0   
..                   ...            ...                ...               ...   
89                  2142          21272               1636              2589   
90                  2162          22101               1676              2636   
91                  2162          23181               1691              2738   
92                  2208          24546               1753              2846   
93                  2239          25811               1827              2970   

                      4                       5                      6     \
0   Los Angeles:California  Santa Clara:California  Suffolk:Massachusetts   
0                        0                       0                      0   
1                        0                       0                      0   
2                        0                       0                      0   
3                        0                       0                      0   
..                     ...                     ...                    ...   
89                   12341                    1870                   8074   
90                   13816                    1922                   8314   
91                   15140                    1946                   8669   
92                   16435                    1962                   9060   
93                   17508                    1987                   9739   

                        7               8                     9     ...  \
0   San Francisco:California  Dane:Wisconsin  San Diego:California  ...   
0                          0               0                     0  ...   
1                          0               0                     0  ...   
2                          0               0                     0  ...   
3                          0               0                     0  ...   
..                       ...             ...                   ...  ...   
89                      1160             361                  2268  ...   
90                      1219             364                  2325  ...   
91                      1234             381                  2434  ...   
92                      1236             386                  2491  ...   
93                      1305             387                  2643  ...   

                2826                2827           2828            2829  \
0   Sherman:Nebraska  Harding:New Mexico  Cochran:Texas  Jim Hogg:Texas   
0                  0                   0              0               0   
1                  0                   0              0               0   
2                  0                   0              0               0   
3                  0                   0              0               0   
..               ...                 ...            ...             ...   
89                 0                   0              0               0   
90                 0                   0              0               0   
91                 0                   0              0               0   
92                 0                   0              0               0   
93                 1                   1              1               1   

               2830         2831          2832          2833         2834  \
0   Fulton:Arkansas  Gray:Kansas  Kiowa:Kansas  Clark:Kansas  Rice:Kansas   
0                 0            0             0             0            0   
1                 0            0             0             0            0   
2                 0     

In [73]:
county_id = pd.read_csv(path+'covid-19-dataset/nssac_county_data.csv')

In [74]:
county_id.head()

FIPS   County  Province_State  Country_Region         Last_Updated  \
0  1001.0  Autauga         Alabama             USA  2020-05-08 00:00:00   
1  1003.0  Baldwin         Alabama             USA  2020-05-08 00:00:00   
2  1005.0  Barbour         Alabama             USA  2020-05-08 00:00:00   
3  1007.0     Bibb         Alabama             USA  2020-05-08 00:00:00   
4  1009.0   Blount         Alabama             USA  2020-05-08 00:00:00   

    Latitude   Longitude   Confirmed   Deaths   Recovered   Active  
0  32.534920  -86.642749          61        3           0       58  
1  30.660970  -87.749840         205        5           0      200  
2  31.869603  -85.393197          51        1           0       50  
3  32.998644  -87.126439          44        0           0       44  
4  33.980867  -86.567371          44        0           0       44

In [80]:
county_state = county_id[' County']+':'+county_id[' Province_State']
county_id['county_state'] = county_id[' County']+':'+county_id[' Province_State']

In [82]:
county_id = county_id[['FIPS', 'county_state']]

In [94]:
county_id = county_id.dropna()

In [143]:
county_id['FIPS'].to_list()

[1001,
 1003,
 1005,
 1007,
 1009,
 1011,
 1013,
 1015,
 1017,
 1019,
 1021,
 1023,
 1025,
 1027,
 1029,
 1031,
 1033,
 1035,
 1037,
 1039,
 1041,
 1043,
 1045,
 1047,
 1049,
 1051,
 1053,
 1055,
 1057,
 1059,
 1061,
 1063,
 1065,
 1067,
 1069,
 1071,
 1073,
 1075,
 1077,
 1079,
 1081,
 1083,
 1085,
 1087,
 1089,
 1091,
 1093,
 1095,
 1097,
 1099,
 1101,
 1103,
 1105,
 1107,
 1109,
 1111,
 1113,
 1117,
 1115,
 1119,
 1121,
 1123,
 1125,
 1127,
 1129,
 1131,
 1133,
 2020,
 2020,
 2050,
 2090,
 2110,
 2122,
 2130,
 2150,
 2170,
 2180,
 2195,
 2198,
 2220,
 2240,
 2290,
 4001,
 4003,
 4005,
 4007,
 4009,
 4011,
 4012,
 4013,
 4015,
 4017,
 4019,
 4021,
 4023,
 4025,
 4027,
 5001,
 5003,
 5005,
 5007,
 5009,
 5011,
 5015,
 5017,
 5019,
 5021,
 5023,
 5025,
 5027,
 5029,
 5031,
 5033,
 5035,
 5037,
 5039,
 5041,
 5043,
 5045,
 5047,
 5049,
 5051,
 5053,
 5055,
 5057,
 5059,
 5061,
 5063,
 5065,
 5067,
 5069,
 5071,
 5073,
 5075,
 5077,
 5079,
 5083,
 5085,
 5087,
 5089,
 5091,
 5093,
 5095,

In [98]:
county_id['FIPS'] = county_id['FIPS'].astype('int32')

C:\Users\ah3wj\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


**Now edgeid list**

In [114]:
adj = pd.read_csv(path+'covid-19-dataset/county_neighbors.csv')  

In [115]:
adj = adj[['Source', 'Destination']]

In [116]:
adj = adj.to_csv(path+'covid-19-dataset/correct_county_edge_id_list.csv', header = False, index=False)

**Now networkx**

In [125]:
graph = nx.read_edgelist(path+'covid-19-dataset/correct_county_edge_id_list.csv', delimiter=',')

In [128]:
len(graph)

3223

In [131]:
nx.write_adjlist(G=graph, path=path+'covid-19-dataset/correct_county_adj_id_list.csv', delimiter=',')

In [140]:
adj_id = pd.read_csv(path+'covid-19-dataset/correct_county_adj_id_list.csv', header=None, dtype='string')

In [147]:
adj_id[adj_id.iloc[:,0].isin(county_id['FIPS'].to_list())]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Index: []

**Now finalize**

In [158]:
final_data = pd.read_csv(path+'covid-19-dataset/processed-data/correct-county-cases.csv')