In [1]:
import pandas as pd
import numpy as np

In [2]:
path = 'C:/Users/ah3wj/Desktop/epi-segmentation/'
df = pd.read_csv(path + 'covid-19-dataset/us-counties.csv')

In [3]:
df.head()

date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1       0
1  2020-01-22  Snohomish  Washington  53061.0      1       0
2  2020-01-23  Snohomish  Washington  53061.0      1       0
3  2020-01-24       Cook    Illinois  17031.0      1       0
4  2020-01-24  Snohomish  Washington  53061.0      1       0

In [4]:
df.state.head()

0    Washington
1    Washington
2    Washington
3      Illinois
4    Washington
Name: state, dtype: object

In [7]:
df['date'] = df['date'].astype('datetime64[ns]')

In [8]:
df.sort_values(by = ['date'], inplace = True, ascending = True)

In [9]:
all_dates = df.date.unique()
print(len(all_dates))

94


In [10]:
all_states = df.state.unique()
print(len(all_states))

56


In [11]:
def preprocess(lookup, resolution):
  with open(path + 'covid-19-dataset/processed-data/processed-us-states-' + lookup + '.csv', 'w+') as lookup_file:

    with open(path + 'covid-19-dataset/processed-data/us-states-order.csv', 'w+')  as order_file:

      for state in all_states:
        print(state + '\n', end='')
        order_file.write(state + '\n')

        for date in all_dates:
          filter1 = df[resolution] == state
          filter2 =  df['date'] == date

          if((filter1 & filter2).any()):
            value = df.loc[filter1 & filter2][lookup].to_string(index=False)
          else:
            value = '0'

          if(date == all_dates[-1]):
            print(value , end='')
            lookup_file.write(value)
          else:
            print(value + ', ', end='')
            lookup_file.write(value + ', ')

        print('\n')
        lookup_file.write('\n')

In [12]:
########################### careful here 

lookup = 'cases'
resolution = 'state'

preprocess(lookup= lookup, resolution = resolution)


Washington
 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  5,  5,  5,  5,  7,  10,  17,  23,  32,  47,  75,  86,  110,  141,  179,  279,  338,  419,  511,  609,  675,  794,  908,  1026,  1228,  1404,  1655,  1844,  2101,  2469,  2585,  3208,  3770,  4311,  4896,  5179,  5292,  5588,  6585,  6966,  7498,  7984,  8384,  8682,  9097,  9608,  9887,  10224,  10411,  10538,  10694,  10783,  11152,  11445,  11802,  11805,  12191,  12345,  12539,  12906

Illinois
0, 0, 0,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  4,  4,  4,  5,  6,  6,  7,  11,  19,  25,  32,  46,  66,  94,  104,  159,  286,  420,  583,  751,  1047,  1285,  1535,  1875,  2538,  3029,  3547,  4613,  5070,  5994,  6980,  7695,  8904,  10357,  11276,  12262,  13549,  15078,  16422,  17887,  19180,  20852,  22025,  23247,  24593,  257

0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  1,  1,  1,  3,  4,  7,  8,  18,  26,  32,  39,  52,  73,  98,  155,  237,  312,  424,  522,  679,  806,  981,  1180,  1364,  1570,  1721,  2049,  2690,  2869,  3032,  3265,  3538,  3753,  4010,  4246,  4456,  4793,  4983,  5144,  5483,  5654,  5878,  6090,  6438,  6637,  6845,  7015,  7341,  7704,  8230

Maryland
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  3,  3,  3,  5,  6,  9,  13,  13,  18,  27,  32,  39,  57,  85,  108,  150,  195,  245,  290,  349,  423,  581,  775,  1066,  1244,  1414,  1662,  1985,  2331,  2758,  3125,  3609,  4045,  4371,  5529,  6185,  6968,  7694,  8225,  8936,  9472,  10032,  10784,  11572,  12308,  12830,  13684,  14193,  14775,  15737

Colorado
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  5,  8,  8,  9,  9,  9,  10,  11,  11,  14,  14,  14,  21,  28,  30,  41,  46,  58,  68,  90,  101,  108,  129,  165,  187,  212,  240,  288,  320,  393,  447,  536,  626,  730,  868,  988,  1168,  1311,  1411,  1542,  1635,  1685,  1755,  1858,  1956

Michigan
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  2,  2,  12,  25,  33,  53,  54,  65,  80,  334,  548,  787,  1033,  1324,  1791,  2294,  2878,  3657,  4635,  5486,  6508,  7630,  9293,  10791,  12670,  14225,  15635,  17130,  18852,  20220,  21375,  22646,  23853,  24494,  25487,  26844,  27893,  29119,  29952,  30717,  31348,  31927,  32935,  33929,  35252

New Mexico
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

**Now Time to Verify**

In [119]:
filename = path + 'covid-19-data/processed-data/processed-us-states-' + lookup + '.csv'
verification = np.loadtxt(filename, dtype=int, delimiter=',')

print(verification)

[[   0    0    0 ...  683  696  717]
 [   0    0    0 ... 1479 1577 1696]
 [   0    0    0 ... 1316 1425 1553]
 ...
 [   0    0    0 ...   26   29   31]
 [   0    0    0 ...    2    2    2]
 [   0    0    0 ...    0    0    0]]


In [120]:
flag = False

for i in range(len(verification)):

  if(flag):
    break
    
  state = all_states[i]   
#   print(state)
  for j in range(len(verification[i])):
    if(verification[i][j] != 0):
      date = all_dates[j]

#       print(date)
      
      df_of_state = df[df[resolution]== state]
      df_of_time = df_of_state[df_of_state['date'] == date]
      value = int(df_of_time[lookup].to_string(index=False))
      
      assert value == verification[i][j]
      if( value != verification[i][j]):
        print("Doesn't match", state, date)
        print('verif index: ', j, 'value: ', verification[i][j])
        print('actual: ', value)
        flag = True
        break
        


In [23]:
states_order = pd.read_csv(path+'covid-19-dataset/processed-data/us-states-order.csv', header=None)
data = pd.read_csv(path+'covid-19-dataset/processed-data/processed-us-states-cases.csv', header=None)

In [28]:
states_order.head()

0
0     Washington
1       Illinois
2     California
3        Arizona
4  Massachusetts

In [29]:
data.head()

0   1   2   3   4   5   6   7   8   9   ...     84     85     86     87  \
0   1   1   1   1   1   1   1   1   1   1  ...  10694  10783  11152  11445   
1   0   0   0   1   1   1   1   1   1   2  ...  23247  24593  25734  27575   
2   0   0   0   0   1   2   2   2   2   2  ...  25758  27107  28142  29398   
3   0   0   0   0   0   1   1   1   1   1  ...   3806   3962   4234   4507   
4   0   0   0   0   0   0   0   0   0   0  ...  28163  29918  32181  34402   

      88     89     90     91     92     93  
0  11802  11805  12191  12345  12539  12906  
1  29160  30357  31508  33059  35108  36935  
2  30829  31544  33862  35844  37573  39534  
3   4719   4929   5064   5251   5459   5769  
4  36372  38077  39643  41199  42944  46023  

[5 rows x 94 columns]

In [24]:
frames = [states_order, data]

In [32]:
result = pd.concat(frames, axis = 1)

In [33]:
result.head()

0   0   1   2   3   4   5   6   7   8   ...     84     85  \
0     Washington   1   1   1   1   1   1   1   1   1  ...  10694  10783   
1       Illinois   0   0   0   1   1   1   1   1   1  ...  23247  24593   
2     California   0   0   0   0   1   2   2   2   2  ...  25758  27107   
3        Arizona   0   0   0   0   0   1   1   1   1  ...   3806   3962   
4  Massachusetts   0   0   0   0   0   0   0   0   0  ...  28163  29918   

      86     87     88     89     90     91     92     93  
0  11152  11445  11802  11805  12191  12345  12539  12906  
1  25734  27575  29160  30357  31508  33059  35108  36935  
2  28142  29398  30829  31544  33862  35844  37573  39534  
3   4234   4507   4719   4929   5064   5251   5459   5769  
4  32181  34402  36372  38077  39643  41199  42944  46023  

[5 rows x 95 columns]

In [37]:
correct_format = result.T

In [40]:
correct_format.to_csv(path+'covid-19-dataset/processed-data/correct-state-cases.csv', header = False, index = False)

In [42]:
adj = pd.read_csv(path + 'covid-19-dataset/processed-data/us-adj.csv', header=None)

In [43]:
adj.head()

0           1            2          3            4          5  \
0      Alaska      Alaska          NaN        NaN          NaN        NaN   
1     Alabama     Alabama  Mississippi  Tennessee      Georgia    Florida   
2    Arkansas    Arkansas     Missouri  Tennessee  Mississippi  Louisiana   
3     Arizona     Arizona   California     Nevada         Utah   Colorado   
4  California  California       Oregon     Nevada      Arizona        NaN   

            6         7    8    9  
0         NaN       NaN  NaN  NaN  
1         NaN       NaN  NaN  NaN  
2       Texas  Oklahoma  NaN  NaN  
3  New Mexico       NaN  NaN  NaN  
4         NaN       NaN  NaN  NaN

In [44]:
states = adj.iloc[:, 0]

In [54]:
states.to_list()

['Alaska',
 'Alabama',
 'Arkansas',
 'Arizona',
 'California',
 'Colorado',
 'Connecticut',
 'DC',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Iowa',
 'Idaho',
 'Illinois',
 'Indiana',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Massachusetts',
 'Maryland',
 'Maine',
 'Michigan',
 'Minnesota',
 'Missouri',
 'Mississippi',
 'Montana',
 'North Carolina',
 'North Dakota',
 'Nebraska',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'Nevada',
 'New York',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Virginia',
 'Vermont',
 'Washington',
 'Wisconsin',
 'West Virginia',
 'Wyoming']

In [48]:
correct_format = pd.read_csv(path+'covid-19-dataset/processed-data/correct-state-cases.csv')

In [56]:
final_data = correct_format[ states.to_list() ]

In [58]:
final_data.to_csv(path+'covid-19-dataset/processed-data/final-us-state-cases.csv', index=False)